### ISSUE TITLE
About the cache FAQ

### ISSUE THREAD

**Issue by VanderSP** [CyCraft/magnetar#28]
Hi very congratulations for all your excellent work... im starting to use data in all this modern js world in a nice moment... and i was looking into vuex then vuex orm, then i found you, then i found magnetar... what you suggest to a production thing, magnetar as it is today, or stick with easy firestore at moment?

ah yes the topic.... i seen your SO post about the pricing, but i´ve also seen another one

https://www.javaer101.com/fr/article/35020648.html

im really confuse...

THANKS FOR EVERYTHING!!!!

**Comment by mesqueeb** [comment]
@VanderSP thanks a lot for finding me!

Magnetar is almost production ready. I am working out the last kinks and minor issues. Also still plan to improve the docs.

I myself already use it in my own production apps, because when I do find a bug I can immediately fix it here myself. : )

### about costs

Currently using magnetar has these price benefits:
- it's easy to keep your local data cached through the session, so every document is only read once in a session from firestore
- in the future I plan to add a "localStorage" plugin that will cache documents for you, so you can even decide to not do new reads if the last cache is only x hours/days old. This will enable even more cost reductions but this will depend on when you decide to execute read commands.

just remember, calling `fetch` or `stream` will always pass the request to firestore SDK and thus you will be charged. So the idea is you try to call `fetch` or `stream` as little as possible.

I also think however, firestore is so cheap that these things generally don't matter too much, unless you are already making a lot of money and have a lot of users.

### about magnetar vs vuex

so I built `vuex-easy-firestore` before, but I got to a point where I don't like Vuex any more.

Magnetar uses code similar to Vuex so it's a replacement for Vuex. You don't need Vuex because magnetar, just like Vuex enables Vue reactivity properly on your cached data.

Personally, the reason I don't like Vuex is:
- too cumbersome, too much setup you need
- no auto completion in your code editor because of weird "calling actions via string" system
- no type safety
- not typescript compatible unless you use 3rd party plugins/wrappers on top of Vuex

Magnetar is super easy, written in typescript, and way better auto completion for any action you can use.

Magnetar does not have the concept of "getters" so you'll need to only use computed properties of your Vue components.
I'm still thinking about what I wanna do about this. We can talk about it if you want, I think it might be better to just do it in your Vue components.

Also, magnetar is already compatible with Vue 2 and Vue 3 via separate plugins, so no worries there either.

I'd say give it a try and definitely let me know what you think! I plan to do some more marketing to get more users soon.

**Comment by VanderSP** [comment]
Nice to read your reply!!!

So with this new reactivity, it works even better with Blitzar? i didn´t tried easy firsetore with blitzar yet... but im thinking in give a try in magnetar/blitzar (hey there´s a bunch of gh projects called magnetar lol)

I´ve got a obscure feeling about the fs cache, because they explain in the docs

https://firebase.google.com/docs/firestore/manage-data/enable-offline

in a way that leads to understand that it would not be priced, however your conversation with van puff is strange when dealing with repetition or queries... while in another s.o. conversation they say that isn´t... sorry insisting about this confusion!

**Comment by mesqueeb** [comment]
> I just want to add that this cache topic makes me more confused when i think about consistency, how exactly u know later that something has changed? :S this is very trippy

I think the answer to this is just "you don't know"
as long as you only read from cache, there's no way to know if it's been updated on the server or not
if you wanna know that you gotta pay a read, that's basically the tradeoff : P
