### ISSUE TITLE
test(firestore): overwriting syncDebounceMs on the action level doesn't work

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/magnetar#60]
> I create a Magnetar instance with a syncDebounceMs of 10000 specified for the Firestore plugin.
>
> Then
> `docRef.merge({ data: 'a' })`
>
> Wait 5s and then
> `docRef.merge({ data: 'b' }, { syncDebounceMs: 0 })`
>
> Wait 6s more and then
> `docRef.merge({ data: 'c' }, { syncDebounceMs: 0 })`
> 
> **expected**: If syncDebounceMs of 0 was to result in any pending changes being flushed out, then I would expect the first two merges to be applied together at about 5s from the first call to merge. The third merge should then occur at about 11s from the first merge call.
>
> **actual**: Instead, what I am seeing is all three merges being applied together at about 21s after the first call to merge. It would appear that the debounce timer is simply being reset to the syncDebounceMs value of the first merge instead of picking up the new debounce value.

@wifisher

if you have some bandwidth to try and write an automated test based on your findings above, it would greatly help me to come in and fix the issue!

The automated test can be added in this file, and you can simply copy paste parts of other tests and then tweak:
https://github.com/cycraft/magnetar/blob/production/packages/plugin-firestore/test/internal/multipleWrites.ts

if not let's keep this issue open for a while until I find time to do it.

**Comment by wifisher** [comment]
I have spent a bit of time looking through the code trying to understand how `syncDebounceMs` is used and, as such, how it is supposed to work.

It looks like the debounce time is supposed to work as the amount of time to wait after a mutation for another mutation to occur. If a mutation occurs during the debounce time, the counter is reset. This then allows for another debounce time for the next mutation. If another mutation does not occur during the debounce time, the mutations get flushed out to Firestore.

This means that with a continuous rate of mutations with each mutation occurring within the debounce time, that nothing will get flushed to Firestore until `MAX_OPERATION_COUNT` is hit. There are also certain mixes of mutations that result in `forceSyncEarly()` being called to flush out queued mutations for consistency reasons.

The other way it could work would be to only queue up mutations that occur within `syncDebounceMs` of each other. For this implementation, it would mean that a mutation was guaranteed to be flushed to Firestore by the end of the debounce time.

I prefer the first method and it appears as though that is the intent of current implementation.

In looking through the code, it appears that the duration of the countdown timer is fixed at the time of its creation. It can be `restart()`ed but otherwise, the duration cannot be changed.

What this means is that the actual debounce time is determined by the first queued mutation. That time could be the default debounce value or the value specified by that particular transaction.

To fix this, I think that the Countdown timer needs a new method such as `changeDuration(ms)` that will change the duration of the timer.

Then `prepareCountdown()` and `triggerSync()` in BatchSync should be changed to something similar to the following:

```
 function prepareCountdown(debounceMsOverwrite?: number): CountdownInstance {
   const ms = isNumber(debounceMsOverwrite) ? debounceMsOverwrite : syncDebounceMs

   if (state.countdown) {
      state.countdown.restart()
      state.countdown.changeDuration(ms)
   } else {
      state.countdown = Countdown(ms)
      state.countdown.done.then(() => executeSync())
   }
   return state.countdown
 }

 function triggerSync(debounceMsOverwrite?: number): void {
    prepareCountdown(debounceMsOverwrite)
 }
```

This change would alter the behaviour so that the debounce time being used is that of the most recent mutation.

Does this fit with your intentions?

**Comment by mesqueeb** [comment]
@wifisher yeah, you are right!

we'll have to change the debounce duration just before we restart the timer.

I'd even say, we can have a syntax like this:
```js
state.countdown.restart({ newDuration: ms })
```
we can pass the `newDuration` any time on the restart function no matter what.
Because if it's not provided by the action it will default to the one set on the module or the global one.

Passing the `newDuration` every time and making a small change inside `Countdown.ts` should be a good enough fix.

The hard part though, is writing a failing automated test. 😅 

The ideal workflow is:
1. replicate the bug as an automated bug and make sure that test fails
2. make the implementation in the source code to fix the issue and continue tinkering until your failing test succeeds

Can you try your hand at creating such a test? : )

**Comment by wifisher** [comment]
I pushed a couple of tests to my syncDebounce branch but they are not well tested. I started getting quota related errors after a few runs while I was figuring out how the tests work.

The two new tests just look at the basic timing. Nothing there yet for flush/sync yet or for various debounce times.

I might have a bit of time tomorrow to look at it some more. Not sure.

**Comment by wifisher** [comment]
PR #62 has the changes to the countdown timer and adds a few tests that look at the timing of the Firestore operations.

**Comment by mesqueeb** [comment]
@wifisher thanks for the PR. Released in 

 - @magnetarjs/core@0.2.12
 - magnetar@0.4.14
 - @magnetarjs/plugin-firestore@0.3.14
